language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-android-m2repository
    - extra-android-support

before_install:
  - sudo rm -r /usr/local/gradle
  - curl -LO http://services.gradle.org/distributions/gradle-2.2.1-bin.zip
  - unzip -q gradle-2.2.1-bin.zip
  - sudo mv gradle-2.2.1 /usr/local/gradle

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: gradle connectedAndroidTest